### PR TITLE
Fix issue #19 (doubled dice button)

### PR DESCRIPTION
**Pull request by caesiumtea**
Closes issue #19

Deletes the extra `<div>` and puts the button styles onto the new `<button>` element instead.

This PR also adds two useless commits: a local commit I had never synced, which conflicted with the newest remote version, and then a commit to resolve the merge conflict by removing my unsynced changes.

### CODE REVIEW

**Review by WitchDevelops — APPROVED** [review]

**Review by WitchDevelops — APPROVED** [review]

**Comment by DevLoggith** [comment]
I also see there were some debugging borders/outlines added to the CSS. I think we should wait to merge the changes until after the debugging is finished and those borders/outlines are deleted.

**Comment by car2t** [comment]
Hey @DevLoggith 

Well, I guess you are right Logan, not necessary all that `box-sizing` code in this app. I got exciting I guess. ;D
 
About the `font-size`...we also could use pixels everywhere but it does not seem right for me since is not accessible for everyone. If you thing is better, no problem. It doesn't change much right?: it should be 16px most of the time. Do you see any issue with that? I am not sure.

I did not remember the dinamic variables. I did not read the specification for them also, so If you think is better...just do it. ;D

**Review by nikkehtine — APPROVED** [review]

**Review by nikkehtine — CHANGES_REQUESTED** [review]
This doesn't look right. `--fs-quote` and `--fs-title` have the same size of `1.75rem`, but the latter isn't used anywhere in the stylesheet

**Review by nikkehtine — APPROVED** [review]

**Comment by nikkehtine** [comment]
Excuse me, still trying to get a hang of the review feature 😅

**Comment by caesiumtea** [comment]
@DevLoggith 
> @car2t I'm a little confused about the CSS reset additions ([566a345](https://github.com/commIT-Group/Advice-generator-app/commit/566a34527e2767e7dfb083b3ce7f8c0d611de761)). We have `box-sizing: border-box` applied to the HTML on line 5, but yet its overwritten later (on line 18) by the `*, *::before, *::after` selectors and the `box-sizing: inherit;` property/value there. Maybe there's something I'm missing and please correct me if I'm wrong! 
Oh, I think I know what this one is about! It can be useful putting `box-sizing: border-box` on just `html` and then `box-sizing: inherit` on everything because it works like this: if you never change the box sizing of individual elements, then it all inherits `box-sizing: border-box` from the root `html`. But this way, if you have an area (like, a certain `div`) where you want to use a different box sizing, then it makes everything inside that `div` follow the same sizing without having to individually set it on every element.

BUT, you're right, it's currently pointless because of the ordering. We need to move the `*` rule up to the top of the file so that it doesn't just overwrite the `html` rule. 

> Also, for this application, do we need to specify `font-size: 100%;` on the HTML, or could we just specify the font size we need for a specific element later in the CSS to reduce redundancy? Instead of using `html, body {height: 100%;}` we could specify `html, body {height: 100dvh;}`. that might have the potential to cause less problems down the road.
@car2t What's the purpose of all of these 100% rules anyway?

**Comment by caesiumtea** [comment]
> About the `font-size`...we also could use pixels everywhere but it does not seem right for me since is not accessible for everyone. If you thing is better, no problem. It doesn't change much right?: it should be 16px most of the time. Do you see any issue with that? I am not sure.

The reason we put a font size in pixels is that the Frontend Mentor instructions say the quote should be 28px, and we want to make sure it will be 28px across all browsers. https://github.com/commIT-Group/Advice-generator-app/blob/main/design/style-guide.md#body-copy  
We said 16px for root because that's the default for most browsers, right?

**Comment by DevLoggith** [comment]
> But this way, if you have an area (like, a certain div) where you want to use a different box sizing, then it makes everything inside that div follow the same sizing without having to individually set it on every element.

@caesiumtea Ahhhh ok, that does make sense. So all we have to do then is just flip the order of the selectors in the CSS file then and everything should work properly?

**Comment by DevLoggith** [comment]
P.S. it looks like the PR was merged and closed already sooooo... 😂 lol

**Comment by caesiumtea** [comment]
@DevLoggith I actually did push a commit just now to flip that order in the CSS file, so it's done! https://github.com/commIT-Group/Advice-generator-app/commit/6e4ac937f1596f402108f5d3202edd1b99967d2e 
(I pushed directly to `main` by accident though >_< So if it turns out I was wrong, we'll have to undo this commit.)

Haha yeah I know the PR is closed, but I think it's still useful to carry on the conversation here so that we all understand the reasons behind these changes!

**Comment by car2t** [comment]
Box sizing 

Hi @caesiumtea @DevLoggith 

Thank you for the explanation Vance; I did not know how, not easy sometimes just study in english.  
I was trying to recall a good article for this... CSS Tricks has a few, but the correct order is the `html` tags first and then `*`.

 [A old article about this](https://www.paulirish.com/2012/box-sizing-border-box-ftw/)

**Comment by car2t** [comment]
`html { font-size: 100%; }`

This code is for to make sure the person have what it needs, not what we want, even though it will work as the challenge says; witch I don't think is the most important, right? I think we should follow the instructions but trying to make something good and modern.

Most of the users will get the default value for `font-size` and our `em` and `rem` units will work fine, but still those users with some vision problems will get what they need. Not sure how to explain better in english.

I hope it make sense.

**Comment by car2t** [comment]
I will let you guys make the code work.
We always can check after if is working or need some improvement, right? No problemo.
Good job!!!

**Comment by WitchDevelops** [comment]
Oooh, now I read what you guys wrote here and `font-size: 100%` makes sense (unless it overwrites user settings? not sure, it's the first time I encounter it). Sorry for reverting back to 16px!

**Comment by car2t** [comment]
It does the opposite @WitchDevelops Domi ;D

**Pull request merged**
