### PR TITLE
HTML minor changes

### PR DESCRIPTION
**Pull request by car2t**
Hi all!

I have corrected my last pull request from `html` branch, and just left dots deletions, `alt=""` for dividers images. 
I left dice image `alt` and footer as it was; and not div wrapping all.

Let's see how it looks now.

### CODE REVIEW

**Comment by caesiumtea** [comment]
So this PR takes out the quote marks from the HTML... do we already have something set up to add them back in through the CSS?

**Review by caesiumtea — APPROVED** [review]

**Comment by car2t** [comment]
> So this PR takes out the quote marks from the HTML... do we already have something set up to add them back in through the CSS?

Hi Vance!

Yeah! It is easy, just a couple of pseudo elements will do the job. After, if anyone wants a fancy ones, we can add it.

Thank you for checking!

**Comment by nikkehtine** [comment]
I guess we don't need this merge if we already have those changes done on #45

**Comment by caesiumtea** [comment]
> I guess we don't need this merge if we already have those changes done on #45  

Actually we do still need it because it adds some alt text and stuff!

**Review by WitchDevelops — APPROVED** [review]

**Comment by WitchDevelops** [comment]
I see lots of code deleted and lots added, I think it's because of formatting? maybe we could some up with some solution to prevent this, so it's easier to see only the changes that are not only due to code formatting. Standardize it, so to speak.

**Comment by nikkehtine** [comment]
I don't know why it shows that 2/3rd of the file has been changed, the majority of those supposedly changed lines seem exactly the same. It makes it so hard to see what was changed

**Comment by nikkehtine** [comment]
> I see lots of code deleted and lots added, I think it's because of formatting? maybe we could some up with some solution to prevent this, so it's easier to see only the changes that are not only due to code formatting. Standardize it, so to speak.

I use an extension called Prettier which automatically formats code on save, keeping it clean and consistent

**Pull request merged**
